#!/usr/bin/env python3

from helpers import credentials
import requests
import sys
import webbrowser

API_URL = "https://api.pinboard.in/v1/"
DELETE_URL = API_URL + "posts/delete"
POSTS_URL = API_URL + "posts/all"
AUTH = credentials.token()


class Bookmark(object):
    def __init__(self, item):
        self.url = item["href"]
        self.unread = item["toread"] == "yes"
        self.hastags = len(item["tags"]) != 0

    def delete(self):
        requests.get(DELETE_URL, auth=AUTH, params={"url": self.url})


def get_items():
    response = requests.get(POSTS_URL, auth=AUTH, params={"format": "json"})
    items = map(Bookmark, response.json())
    return [item for item in items if item.unread]


def usage(prg):
    print("Usage: %s [COUNT]" % prg)
    sys.exit(2)


def main(count):
    items = get_items()
    if count == -1:
        count = len(items)
    for i in range(count):
        if i >= len(items):
            break

        item = items[i]
        if webbrowser.open_new_tab(item.url):
            item.delete()


if __name__ == '__main__':
    if len(sys.argv) != 2:
        usage(sys.argv[0])
    try:
        open_count = int(sys.argv[1])
    except ValueError:
        usage(sys.argv[0])

    try:
        main(open_count)
    except KeyboardInterrupt:
        sys.exit(1)
